config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:reviews_pk>/comments", views.comment_create, name="comment_create"),
    path(
        "<int:reviews_pk>/comments/<int:comment_pk>/update",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:reviews_pk>/comments/<int:comment_pk>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
]

reviews/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail

# Create your models here.


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[Thumbnail(100, 100)],
        format="JPEG",
        options={"quality": 80},
    )


class Comment(models.Model):
    article = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "content",
            "image",
            "thumbnail",
        ]
        labels = {
            "title": "제목",
            "content": "내용",
            "image": "이미지",
            "thumbnail": "썸네일",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]
        labels = {
            "content": "댓글",
        }

reviews/views.py
from multiprocessing import context
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from reviews.forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    k = Review.objects.all().order_by("-id")
    page = request.GET.get("page", "1")  # 페이지
    paginator = Paginator(k, 3)
    page_obj = paginator.get_page(page)
    context = {
        "v": k,
        "question_list": page_obj,
    }

    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
    context = {
        "create_form": review_form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, pk):
    k = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = k.comment_set.all()
    context = {
        "i": k,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def delete(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect("reviews:index")
    return redirect("reviews:detail", review.pk)


@login_required
def update(request, pk):
    k = get_object_or_404(Review, pk=pk)
    if request.user == k.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, request.FILES, instance=k)
            if review_form.is_valid():
                review_form.save()
                return redirect("reviews:index", k.pk)
        else:
            review_form = ReviewForm(instance=k)
        context = {
            "review_form": review_form,
            "k": k,
        }
        return render(request, "reviews/update.html", context)


@login_required
def comment_create(request, reviews_pk):
    article = Review.objects.get(pk=reviews_pk)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
    return redirect("reviews:detail", article.pk)


@login_required
def comment_update(request, article_pk, comment_pk):
    article = Review.objects.get(pk=article_pk)
    comment = Comment.objects.get(pk=comment_pk)

    if request.user != comment.user:
        messages.warning(request, "권한이 없습니다.")
        return redirect("reviews:detail", article.pk)

    if request.method == "POST":
        updated_comment = request.POST.get("updated_comment")
        if 0 < len(updated_comment) <= 80:
            comment.content = updated_comment
            comment.article = article
            comment.save()
            messages.success(request, "댓글 수정 완료")
    else:
        messages.warning(request, "잘못된 접근입니다.")
    return redirect("reviews:detail", article.pk)


@login_required
def comment_delete(request, reviews_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user != comment.user:
        messages.warning(request, "권한이 없습니다.")
        return redirect("reviews:detail", reviews_pk)
    if request.method == "POST":
        comment.delete()
        messages.warning(request, "댓글 삭제 완료")
    else:
        messages.warning(request, "잘못된 접근입니다.")
    return redirect("reviews:detail", reviews_pk)

reviews/templates/reviews/comment_update.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}
  <div class="m-3">
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form layout='inline'%}
      <input type="submit" class="m-2 btn btn-outline-secondary" value="수정">
    </form>
  </div>
{% endblock %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% block title %}CREATE{% endblock title %}
{% block content %}
  {% load django_bootstrap5 %}
  {% load static %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2 ">등록</h5>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form create_form %}
      <input type="submit" class="btn btn-outline-warning my-3" value="등록">
    </form>
  {% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <!-- 게시글 -->
  <div class="p-4">
    <div class="row justify-content-center">

      <div class="col-md-12 col-lg-6">

        <!-- 게시글 head -->
        <div class="bg-light p-3 mb-4" style="border-radius: 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          <h1 class="mb-3 fw-bolder">{{ i.title }}</h1>
          <span>
            작성자:
            {{ i.user }}
          </span>
          <p class="fw-light mb-1 text-end" style="font-size: 0.7rem;">
            {{ i.created_at|date:'Y-m-d a h:i' }}
            작성 |
            {{ i.updated_at|date:'Y-m-d a h:i' }}
            수정
          </p>
        </div>

        <!-- 게시글 body -->
        <div class="bg-white p-3 mb-4" style="border-radius: 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          {% if i.image %}
            <img src="{{ i.image.url }}" alt="{{ i.image }}" class="img-fluid">
          {% endif %}
          <p>{{ i.content }}</p>
          <div class="d-block d-lg-none">
            {% if request.user == i.user %}
              <a href="{% url 'reviews:update' i.pk %}" class="btn btn-outline-secondary form-control mb-3">수정</a>
              <form action="{% url 'reviews:delete' i.pk %}" method="POST" class="form">
                {% csrf_token %}
                <input class="btn btn-outline-danger form-control mb-3" type="submit" value="삭제">
              </form>
            {% else %}
              <a href="" class="btn btn-outline-secondary form-control disabled mb-3">수정</a>
              <a href="" class="btn btn-outline-danger form-control disabled mb-3">삭제</a>
            {% endif %}
            <a href="{% url 'reviews:index' %}" class="btn btn-outline-secondary form-control mb-3">뒤로</a>
          </div>

          <div class="d-none d-lg-block">
            <div class="d-flex justify-content-end">
              {% if request.user == i.user %}
                <a href="{% url 'reviews:update' i.pk %}" class="btn btn-outline-secondary me-1">수정</a>
                <form action="{% url 'reviews:delete' i.pk %}" method="POST" class="form">
                  {% csrf_token %}
                  <input class="btn btn-outline-danger me-1" type="submit" value="삭제"></form>
              {% else %}
                <a href="" class="btn btn-outline-secondary disabled me-1">수정</a>
                <a href="" class="btn btn-outline-danger disabled me-1">삭제</a>
              {% endif %}
              <a href="{% url 'reviews:index' %}" class="btn btn-outline-secondary">뒤로</a>
            </div>
          </div>
        </div>

        <!-- 댓글 -->
        <div class="bg-gray-100 p-3 mb-4" style="border-radius: 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          {% if comments %}
            <p>
              <b>{{ comments|length }}개의 댓글이 있습니다.</b>
            </p>
            <hr>
          {% endif %}

          {% for comment in comments %}
            <div class="comment_display_{{ comment.pk }} d-block">
              <p class="mb-1">{{ comment.content }}</p>

              <p class="text-end">{{ comment.user.username }}</p>

              <p class="fw-light mb-1 text-end" style="font-size: 0.7rem;">
                {{ comment.created_at|date:'Y-m-d a h:i' }}
                작성 |
                {{ comment.updated_at|date:'Y-m-d a h:i' }}
                수정
              </p>

              <div class="d-flex justify-content-end">
                {% if request.user == comment.user %}
                  <div class="mb-3">
                    <button onclick="udate_c()" class="btn btn-sm btn-outline-secondary me-1 update_btn_{{ comment.pk }}">수정</button>

                    <form action="{% url 'reviews:comment_delete' i.pk comment.pk %}" method="POST" class="form">
                      {% csrf_token %}
                      <button class="btn btn-sm btn-outline-danger" type="submit">삭제</button>
                    </form>
                  </div>
                {% endif %}
              </div>

              {% if request.user == comment.user %}
                <div name="comment_u" id="comment_u">
                  <form action="{% url 'reviews:comment_update' i.pk comment.pk %}" method="POST" class="form">
                    {% csrf_token %}
                    <label for="updated_comment" class="form-label">수정하기</label>
                    <input type="text" class="form-control" name="updated_comment" id="updated_comment" maxlength="80" placeholder="댓글" value="{{ comment.content }}" required="required">
                  </form>
                </div>

                <div class="d-flex justify-content-end my-3">
                  <input class="btn btn-sm btn-primary me-1" type="submit" value="완료">
                  <button class="btn btn-sm btn-secondary cancel_btn_{{ comment.pk }}" type="button">취소</button>
                </div>
              {% endif %}
            </div>

            <hr>
            {% empty %}
            <p>
              <b>
                0개의 댓글이 있습니다.</b>
            </p>
            <hr>
          {% endfor %}

          {% if request.user.is_authenticated %}
            <form action="{% url 'reviews:comment_create' i.pk %}" method="POST">
              {% csrf_token %}
              {% bootstrap_form comment_form %}
              <div class="d-flex justify-content-end">
                <input class="btn btn-sm btn-primary" type="submit" value="작성">
              </div>
            </form>
          {% endif %}
        </div>

      </div>
    </div>
  </div>

  <script>
    function udate_c() {
      var con = Document.getElementByld("comment_u");
      con.style.display = (con.style.display != 'none')
        ? "none"
        : "block";
    }
  </script>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block content %}
  <h3 class="text-center my-5">REVIEWS</h3>
  <div class="row m-2">
    {% for i in v %}
      <div class="col-4 mb-2">
        <div class="card" style="width: 18rem border-radius 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          {% if i.thumbnail %}
            <img src="{{ i.thumbnail.url }}" class="card-img-top" alt="" width="400" height="300">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ i.title }}</h5>
            <a href="{% url 'reviews:detail' i.pk %}" class="btn btn-outline-warning my-3">자세히 보기</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- 페이징처리 시작 -->
  <div class="m-3">
    <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if question_list.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="text-warning page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
      {% endif %}
      <!-- 페이지리스트 -->
      {% for page_number in question_list.paginator.page_range %}
        {% if page_number == question_list.number %}
          <li class="page-item" aria-current="page">
            <a class="text-warning page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="text-warning page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if question_list.has_next %}
        <li class="page-item">
          <a class="text-warning page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="text-warning page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
      {% endif %}
    </ul>
  </div>
  <!-- 페이징처리 끝 -->
{% endblock %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}
  <div class="m-3">
    <form action="{% url 'reviews:update' k.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      <input type="submit" class="m-2 btn btn-outline-warning" value="등록">
    </form>
  </div>
{% endblock %}