accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("", views.login, name="login"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
        )


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

# 회원가입
from accounts.forms import CustomUserCreationForm

# 로그인
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login

# 로그아웃
from django.contrib.auth import logout as auth_logout

# 회원정보수정
from accounts.forms import CustomUserChangeForm
from django.contrib.auth.forms import PasswordChangeForm

# 세션 무효화 방지
from django.contrib.auth import update_session_auth_hash

# Create your views here.


def index(request):
    return render(request, "accounts/index.html")


def profile(reqeust, pk):
    profile = get_user_model().objects.get(pk=pk)
    context = {"profile": profile}
    return render(reqeust, "accounts/profile.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    # if request.user.is_authenticated:
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("reviews:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


def delete(request):
    request.user.delete()
    auth_logout(request)
    return render(request, "reviews/index.html")

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}ACCOUNT_CHANGE_PASSWORD{% endblock title %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}ACCOUNT_INDEX{% endblock title %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="container d-flex">
      <a href="{% url 'accounts:profile' user.pk %}">{{user}}</a>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn">
      </form>
    </div>
  {% else %}
    <div class="container">
      <a href="{% url 'accounts:signup' %}">Signup</a>
      <a href="{% url 'accounts:login' %}">Login</a>
    </div>
  {% endif %}
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}ACCOUNT_LOGIN{% endblock title %}

{% block content %}
  <div class="container">
    <h1 class='my-3'>로그인</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-outline-warning my-3">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}DETAIL{% endblock title %}

{% block content %}
  <p>{{ profile.username }}</p>
  <p>{{ profile.first_name }}</p>
  <p>{{ profile.last_name }}</p>
  <p>{{ profile.email }}</p>
  <a href="{% url 'accounts:update' %}">수정</a>
  <a href="{% url 'accounts:delete' %}">삭제</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}ACCOUNT_SIGNUP{% endblock title %}

{% block content %}
  <div class="container">
    <h1 class='my-3'>회원가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-outline-warning my-3" type="submit">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}ACCOUNT_UPDATE{% endblock title %}

{% block content %}
  <div class="container">
    <h1>회원정보수정</h1>
    <form action="{% url 'accounts:update' %}">
      {% csrf_token %}
      {% bootstrap_form form %}
      <a href="{% url 'accounts:change_password'%}">비밀번호 변경</a>
      <input type="submit">
    </form>
  </div>
{% endblock content %}