accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("", views.login, name="login"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:reviews_pk>/comments", views.comment_create, name="comment_create"),
    path(
        "<int:reviews_pk>/comments/<int:comment_pk>/update",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:reviews_pk>/comments/<int:comment_pk>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'reviews:index' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'reviews:create' %}">CREATE</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">{{user}}</a>
              </li>
              <li class="nav-item">
                <form action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="Logout" class="btn text-secondary">
                </form>
              </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
              </li>
            {% endif %}
          </div>
        </div>
      </nav>
      {% block content %}{% endblock %}
    </body>

  </html>